#!/usr/bin/env python3
"""Sync public GitHub Sponsors into lib/sponsors.json.

Reads the Duckurity organization sponsors through the GraphQL API and
writes the login wall data the home sponsor section renders. The site
itself never calls the API: the generated file is committed, so builds
stay deterministic and offline-safe.

Needs SPONSORS_TOKEN: a classic PAT with read:user and read:org, owned
by an organization owner. Same ceremony as WIKI_PUSH_TOKEN. Without the
token the script exits clean and the checked-in data stands.

Curated entries live under the `manual` key in lib/sponsors.json and
survive every sync. Use them for brand-deal sponsors who sit outside
GitHub Sponsors. Each entry needs login, name, url, and avatar.

Usage:
    SPONSORS_TOKEN=ghp_... python3 scripts/sync_sponsors.py
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "lib" / "sponsors.json"
OWNER = os.environ.get("SPONSORS_OWNER", "Duckurity")

QUERY = """
query($owner: String!, $cursor: String) {
  organization(login: $owner) {
    sponsorshipsAsMaintainer(first: 100, after: $cursor, activeOnly: true, includePrivate: false) {
      pageInfo { hasNextPage endCursor }
      nodes {
        sponsorEntity {
          ... on User { login name }
          ... on Organization { login name }
        }
      }
    }
  }
}
"""


def fetch(token: str) -> list[dict[str, str]]:
    sponsors: list[dict[str, str]] = []
    cursor: str | None = None
    while True:
        body = json.dumps(
            {"query": QUERY, "variables": {"owner": OWNER, "cursor": cursor}}
        ).encode("utf-8")
        request = urllib.request.Request(
            "https://api.github.com/graphql",
            data=body,
            headers={
                "Authorization": f"bearer {token}",
                "Content-Type": "application/json",
                "User-Agent": "openlabs-sync-sponsors",
            },
        )
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except Exception as error:
            print(f"sync_sponsors: request failed: {error}", file=sys.stderr)
            raise SystemExit(1)
        if payload.get("errors"):
            print(f"sync_sponsors: {payload['errors']}", file=sys.stderr)
            raise SystemExit(1)
        connection = ((payload.get("data") or {}).get("organization") or {}).get(
            "sponsorshipsAsMaintainer"
        )
        if connection is None:
            print(
                "sync_sponsors: no sponsor data, token likely lacks read:org",
                file=sys.stderr,
            )
            raise SystemExit(1)
        for node in connection.get("nodes", []):
            entity = node.get("sponsorEntity") or {}
            login = entity.get("login", "")
            if not login:
                continue
            sponsors.append(
                {
                    "login": login,
                    "name": entity.get("name") or login,
                    "url": f"https://github.com/{login}",
                    "avatar": f"https://github.com/{login}.png?s=96",
                }
            )
        page = connection.get("pageInfo", {})
        if not page.get("hasNextPage"):
            break
        cursor = page.get("endCursor")
    return sponsors


def load_manual() -> list[dict[str, str]]:
    """Curated entries from the checked-in file. Invalid rows drop out."""
    try:
        raw = json.loads(OUT.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    manual = raw.get("manual", [])
    if not isinstance(manual, list):
        return []
    kept: list[dict[str, str]] = []
    for entry in manual:
        if not isinstance(entry, dict):
            continue
        login = str(entry.get("login", ""))
        if not login:
            continue
        kept.append(
            {
                "login": login,
                "name": str(entry.get("name") or login),
                "url": str(entry.get("url") or f"https://github.com/{login}"),
                "avatar": str(
                    entry.get("avatar") or f"https://github.com/{login}.png?s=96"
                ),
            }
        )
    return kept


def render(manual: list[dict[str, str]], sponsors: list[dict[str, str]]) -> str:
    return (
        json.dumps(
            {
                "_note": "Generated by scripts/sync_sponsors.py. Only the manual key is hand-edited.",
                "manual": manual,
                "sponsors": sponsors,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )


def main() -> int:
    token = "".join(os.environ.get("SPONSORS_TOKEN", "").split())
    if not token:
        print("sync_sponsors: SPONSORS_TOKEN not set, keeping checked-in data")
        return 0
    sponsors = fetch(token)
    manual = load_manual()
    text = render(manual, sponsors)
    if OUT.is_file() and OUT.read_text(encoding="utf-8") == text:
        print(f"sync_sponsors: up to date ({len(sponsors)} sponsors)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"sync_sponsors: wrote {len(sponsors)} sponsors to lib/sponsors.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
